language: android
sudo: false

android:
    components:
        - android-23
        - build-tools-23.0.1
        - extra-android-support
        - extra
    licenses:
        - android-sdk-license-.+

branches:
    only:
        - develop
        - master

env:
    global:
        - secure: CQHPxmlHumWs91whz1y5se5QdONB9sXh8NCDa84OX/ly5ED9FpHlAcUwGOG987jRqWvP1s0UfARm1t2Y9c8xfauVP8ihlnVXTFPWY3ykkx6I4TuV4f4iJpuj7wWXecKi9ruL2dd68e8RCWoXd0KJD1QZ1PGoHblBo8wRFOVFfSM=
        - secure: LBWJkQWRR+5VwZAN2nTHwhJ/qOo90NA2kDqIaEpaiyEaItFQLlh1A7K3Q8KTMj+QVgMhmgr7W5MeTKMRBUzd+8C921gqVfTiy5vh/8nAUh6rzZ6+6xyxgA6ItKO03zyU+gI4KSBIPM+0zcvELu0HwzD/LdrvJ/MgGPF4tQ5oGjo=

before_script:
    - echo no | android create avd --force --name test-avd --target android-21 --abi armeabi-v7a
    - emulator -avd test-avd -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    - ./gradlew clean assemble connectedAndroidTest
